"""Render the host-specific route catalogs from the canonical harness registry.

Shared by ``tools/agents/sync_routes.py`` (which writes them) and ``doctor`` (which
checks them), so the runtime never imports from ``tools/``.
"""

from __future__ import annotations

import copy
import json
from pathlib import Path
from typing import Any

from .catalog import load_catalog


def _display_routes(harness: dict[str, Any]) -> str:
    routes = list(harness["models"])
    routes.extend(
        family["example"] for family in harness["routeFamilies"] if family["example"] not in routes
    )
    labels: list[str] = []
    fallback = harness["defaultModel"]["fallback"]
    source = harness["defaultModel"]["source"]
    if source == "codex-config":
        labels.append("configured Codex default")
    elif source == "kimi-config":
        labels.append("configured Kimi default")
    elif source == "registry" and fallback and fallback not in routes:
        routes.insert(0, fallback)
    labels.extend(f"`{route}`" for route in routes)
    return ", ".join(labels) or "any configured model"


def _display_effort(harness: dict[str, Any]) -> str:
    if harness["effort"]["kind"] == "none":
        return "not supported"
    values = harness["effort"]["values"]
    return ", ".join(f"`{value}`" for value in values) if values else "harness-defined"


def _runtime_references(harness: dict[str, Any]) -> str:
    references: list[str] = []
    for model in harness["models"].values():
        if model["runtimeReference"] not in references:
            references.append(model["runtimeReference"])
    for family in harness["routeFamilies"]:
        if family["runtimeReference"] not in references:
            references.append(family["runtimeReference"])
    return "<br>".join(
        f"[{reference.split('#', 1)[1]}]({reference.removeprefix('references/')})"
        for reference in references
    )


def render_open_models(registry: dict[str, Any], catalog: dict[str, Any]) -> list[str]:
    families = registry.get("modelFamilies", {})
    models = catalog.get("models", {})
    if not families and not models:
        return []
    lines = [
        "## Open-weight models",
        "",
        "Harness-independent families with full seed cards, then the lightweight picker catalog. Route any of them by name through `route-shim.sh`; see `docs/routes.md`.",
        "",
    ]
    if families:
        lines += [
            "| Family | Display name | Models | License | Context | Reasoning control | Runtime reference |",
            "|---|---|---|---|---|---|---|",
        ]
        for family_id, family in families.items():
            reference = family["runtimeReference"]
            lines.append(
                f"| `{family_id}` | {family['displayName']} | "
                + ", ".join(f"`{m}`" for m in family["models"])
                + f" | {family['license']} | {family['contextWindow']} | {family['reasoningControl']['detail']} | "
                f"[{reference.split('#', 1)[1]}]({reference.removeprefix('references/')}) |"
            )
        lines.append("")
    if models:
        lines += [
            "| Catalog id | Model | Vendor | License | Context | Reasoning control | Model card |",
            "|---|---|---|---|---|---|---|",
        ]
        for catalog_id, entry in models.items():
            lines.append(
                f"| `{catalog_id}` | `{entry['modelId']}` | {entry['vendor']} | {entry['license']} | {entry['contextWindow']} | "
                f"{entry['reasoningControl']} | [card](" + entry["modelCardUrl"] + ") |"
            )
        lines.append("")
    return lines


def render_markdown(registry: dict[str, Any], catalog: dict[str, Any]) -> str:
    harnesses = registry["harnesses"]
    lines = [
        "# Generated Route Catalog",
        "",
        "<!-- Generated by tools/agents/sync_routes.py; edit src/pitwall/agents/resources/config/harness-registry.json instead. -->",
        "",
        "A host runs its own native harness directly, not through a shim; the plugin for that host "
        "says which harness that is.",
        "",
        "| Harness | Shim | Known/default routes | Effort values | Runtime reference |",
        "|---|---|---|---|---|",
    ]
    for harness_id, harness in harnesses.items():
        lines.append(
            f"| `{harness_id}` | `~/.claude/scripts/{harness['shim']}` | "
            f"{_display_routes(harness)} | {_display_effort(harness)} | {_runtime_references(harness)} |"
        )
    lines.extend(render_open_models(registry, catalog))
    lines.extend(
        [
            "",
            "Unknown model IDs remain pass-through when the harness CLI accepts them. This catalog is routing guidance, not a live harness availability claim.",
            "",
        ]
    )
    return "\n".join(lines)


def render_json(registry: dict[str, Any]) -> str:
    payload = {
        "schemaVersion": registry["schemaVersion"],
        "hosts": {host_id: host["nativeHarnesses"] for host_id, host in registry["hosts"].items()},
        "harnesses": copy.deepcopy(registry["harnesses"]),
        "modelFamilies": registry.get("modelFamilies", {}),
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


GENERATED_DIR = Path("src/pitwall/agents/resources/generated")


def generated_files(
    registry: dict[str, Any],
    catalog: dict[str, Any] | None = None,
    *,
    root: Path,
) -> dict[Path, str]:
    """The single generated copy of the route references; install copies it into each plugin."""

    catalog = load_catalog(registry=registry) if catalog is None else catalog
    return {
        root / GENERATED_DIR / "routes.generated.md": render_markdown(registry, catalog),
        root / GENERATED_DIR / "harness-registry.generated.json": render_json(registry),
    }
