"""Provider plugin interface, registry, and built-in adapters."""

from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from pitwall.providers.gateway import (
        GatewayCredentials,
        GatewayInferenceResult,
        GatewayProvider,
        GatewayProviderError,
        QuotaExhausted,
    )
    from pitwall.providers.interface import (
        ActualCostProvider,
        ActualCostRequest,
        ActualCostResourceReference,
        AsyncInferenceCancelProvider,
        AsyncInferenceCancelRequest,
        AsyncInferenceCancelResult,
        AsyncInferenceProvider,
        AsyncInferenceRequest,
        AsyncInferenceStatusProvider,
        AsyncInferenceStatusRequest,
        AsyncInferenceStatusResult,
        AsyncInferenceSubmission,
        AvailabilityItem,
        AvailabilityKind,
        AvailabilityProvider,
        AvailabilityRequest,
        AvailabilityResult,
        ComputeProvider,
        CredentialInput,
        CredentialReference,
        CredentialResolutionError,
        InferenceProvider,
        InferenceRequest,
        InferenceResult,
        Provider,
        ProviderAdapter,
        ProviderCapability,
        ProviderOperationContext,
        ProvisionRequest,
        ProvisionResult,
        ReconcileRequest,
        ReconcileResult,
        ResourceStatus,
        StatusRequest,
        StatusResult,
        TeardownRequest,
        TeardownResult,
        resolve_adapter_credentials,
    )
    from pitwall.providers.lambda_cloud import LambdaCloudCredentials, LambdaCloudProvider
    from pitwall.providers.model_studio import (
        ModelStudioCredentials,
        ModelStudioInferenceResult,
        ModelStudioProvider,
        ModelStudioProviderError,
    )
    from pitwall.providers.registry import (
        CredentialValidationError,
        DuplicateProviderError,
        InvalidProviderRegistrationError,
        ProviderNotRegisteredError,
        ProviderRegistry,
        ProviderRegistryError,
        UnsupportedProviderCapabilityError,
        create_default_registry,
        get_default_registry,
    )
    from pitwall.providers.runpod import RunPodCredentials, RunPodProvider
    from pitwall.providers.together import (
        TogetherCredentials,
        TogetherInferenceResult,
        TogetherProvider,
        TogetherProviderError,
    )
    from pitwall.providers.vast import VastCredentials, VastProvider


_LAZY_EXPORTS = {
    "ActualCostProvider": ("pitwall.providers.interface", "ActualCostProvider"),
    "ActualCostRequest": ("pitwall.providers.interface", "ActualCostRequest"),
    "ActualCostResourceReference": ("pitwall.providers.interface", "ActualCostResourceReference"),
    "AsyncInferenceCancelProvider": ("pitwall.providers.interface", "AsyncInferenceCancelProvider"),
    "AsyncInferenceCancelRequest": ("pitwall.providers.interface", "AsyncInferenceCancelRequest"),
    "AsyncInferenceCancelResult": ("pitwall.providers.interface", "AsyncInferenceCancelResult"),
    "AsyncInferenceProvider": ("pitwall.providers.interface", "AsyncInferenceProvider"),
    "AsyncInferenceRequest": ("pitwall.providers.interface", "AsyncInferenceRequest"),
    "AsyncInferenceStatusProvider": ("pitwall.providers.interface", "AsyncInferenceStatusProvider"),
    "AsyncInferenceStatusRequest": ("pitwall.providers.interface", "AsyncInferenceStatusRequest"),
    "AsyncInferenceStatusResult": ("pitwall.providers.interface", "AsyncInferenceStatusResult"),
    "AsyncInferenceSubmission": ("pitwall.providers.interface", "AsyncInferenceSubmission"),
    "AvailabilityItem": ("pitwall.providers.interface", "AvailabilityItem"),
    "AvailabilityKind": ("pitwall.providers.interface", "AvailabilityKind"),
    "AvailabilityProvider": ("pitwall.providers.interface", "AvailabilityProvider"),
    "AvailabilityRequest": ("pitwall.providers.interface", "AvailabilityRequest"),
    "AvailabilityResult": ("pitwall.providers.interface", "AvailabilityResult"),
    "ComputeProvider": ("pitwall.providers.interface", "ComputeProvider"),
    "CredentialInput": ("pitwall.providers.interface", "CredentialInput"),
    "CredentialReference": ("pitwall.providers.interface", "CredentialReference"),
    "CredentialResolutionError": ("pitwall.providers.interface", "CredentialResolutionError"),
    "InferenceProvider": ("pitwall.providers.interface", "InferenceProvider"),
    "InferenceRequest": ("pitwall.providers.interface", "InferenceRequest"),
    "InferenceResult": ("pitwall.providers.interface", "InferenceResult"),
    "Provider": ("pitwall.providers.interface", "Provider"),
    "ProviderAdapter": ("pitwall.providers.interface", "ProviderAdapter"),
    "ProviderCapability": ("pitwall.providers.interface", "ProviderCapability"),
    "ProviderOperationContext": ("pitwall.providers.interface", "ProviderOperationContext"),
    "ProvisionRequest": ("pitwall.providers.interface", "ProvisionRequest"),
    "ProvisionResult": ("pitwall.providers.interface", "ProvisionResult"),
    "ReconcileRequest": ("pitwall.providers.interface", "ReconcileRequest"),
    "ReconcileResult": ("pitwall.providers.interface", "ReconcileResult"),
    "ResourceStatus": ("pitwall.providers.interface", "ResourceStatus"),
    "StatusRequest": ("pitwall.providers.interface", "StatusRequest"),
    "StatusResult": ("pitwall.providers.interface", "StatusResult"),
    "TeardownRequest": ("pitwall.providers.interface", "TeardownRequest"),
    "TeardownResult": ("pitwall.providers.interface", "TeardownResult"),
    "resolve_adapter_credentials": ("pitwall.providers.interface", "resolve_adapter_credentials"),
    "CredentialValidationError": ("pitwall.providers.registry", "CredentialValidationError"),
    "DuplicateProviderError": ("pitwall.providers.registry", "DuplicateProviderError"),
    "InvalidProviderRegistrationError": (
        "pitwall.providers.registry",
        "InvalidProviderRegistrationError",
    ),
    "ProviderNotRegisteredError": ("pitwall.providers.registry", "ProviderNotRegisteredError"),
    "ProviderRegistry": ("pitwall.providers.registry", "ProviderRegistry"),
    "ProviderRegistryError": ("pitwall.providers.registry", "ProviderRegistryError"),
    "UnsupportedProviderCapabilityError": (
        "pitwall.providers.registry",
        "UnsupportedProviderCapabilityError",
    ),
    "create_default_registry": ("pitwall.providers.registry", "create_default_registry"),
    "get_default_registry": ("pitwall.providers.registry", "get_default_registry"),
    "GatewayCredentials": ("pitwall.providers.gateway", "GatewayCredentials"),
    "GatewayInferenceResult": ("pitwall.providers.gateway", "GatewayInferenceResult"),
    "GatewayProvider": ("pitwall.providers.gateway", "GatewayProvider"),
    "GatewayProviderError": ("pitwall.providers.gateway", "GatewayProviderError"),
    "QuotaExhausted": ("pitwall.providers.gateway", "QuotaExhausted"),
    "LambdaCloudCredentials": ("pitwall.providers.lambda_cloud", "LambdaCloudCredentials"),
    "LambdaCloudProvider": ("pitwall.providers.lambda_cloud", "LambdaCloudProvider"),
    "ModelStudioCredentials": ("pitwall.providers.model_studio", "ModelStudioCredentials"),
    "ModelStudioInferenceResult": (
        "pitwall.providers.model_studio",
        "ModelStudioInferenceResult",
    ),
    "ModelStudioProvider": ("pitwall.providers.model_studio", "ModelStudioProvider"),
    "ModelStudioProviderError": ("pitwall.providers.model_studio", "ModelStudioProviderError"),
    "RunPodCredentials": ("pitwall.providers.runpod", "RunPodCredentials"),
    "RunPodProvider": ("pitwall.providers.runpod", "RunPodProvider"),
    "TogetherCredentials": ("pitwall.providers.together", "TogetherCredentials"),
    "TogetherInferenceResult": (
        "pitwall.providers.together",
        "TogetherInferenceResult",
    ),
    "TogetherProvider": ("pitwall.providers.together", "TogetherProvider"),
    "TogetherProviderError": ("pitwall.providers.together", "TogetherProviderError"),
    "VastCredentials": ("pitwall.providers.vast", "VastCredentials"),
    "VastProvider": ("pitwall.providers.vast", "VastProvider"),
}


def __getattr__(name: str) -> Any:
    """Load provider modules only when requested; the package import stays light."""
    target = _LAZY_EXPORTS.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attribute_name = target
    value = getattr(import_module(module_name), attribute_name)
    globals()[name] = value
    return value


__all__ = [
    "ActualCostProvider",
    "ActualCostRequest",
    "ActualCostResourceReference",
    "AvailabilityItem",
    "AvailabilityKind",
    "AvailabilityProvider",
    "AvailabilityRequest",
    "AvailabilityResult",
    "AsyncInferenceCancelProvider",
    "AsyncInferenceCancelRequest",
    "AsyncInferenceCancelResult",
    "AsyncInferenceProvider",
    "AsyncInferenceRequest",
    "AsyncInferenceStatusProvider",
    "AsyncInferenceStatusRequest",
    "AsyncInferenceStatusResult",
    "AsyncInferenceSubmission",
    "ComputeProvider",
    "CredentialInput",
    "CredentialReference",
    "CredentialResolutionError",
    "CredentialValidationError",
    "DuplicateProviderError",
    "GatewayCredentials",
    "GatewayInferenceResult",
    "GatewayProvider",
    "GatewayProviderError",
    "InferenceProvider",
    "InferenceRequest",
    "InferenceResult",
    "InvalidProviderRegistrationError",
    "Provider",
    "ProviderAdapter",
    "ProviderCapability",
    "ProviderNotRegisteredError",
    "ProviderOperationContext",
    "ProviderRegistry",
    "ProviderRegistryError",
    "QuotaExhausted",
    "UnsupportedProviderCapabilityError",
    "ProvisionRequest",
    "ProvisionResult",
    "ReconcileRequest",
    "ReconcileResult",
    "ResourceStatus",
    "RunPodCredentials",
    "RunPodProvider",
    "StatusRequest",
    "StatusResult",
    "TeardownRequest",
    "TeardownResult",
    "TogetherCredentials",
    "TogetherInferenceResult",
    "TogetherProvider",
    "TogetherProviderError",
    "create_default_registry",
    "get_default_registry",
    "resolve_adapter_credentials",
    "VastCredentials",
    "VastProvider",
    "LambdaCloudCredentials",
    "LambdaCloudProvider",
    "ModelStudioCredentials",
    "ModelStudioInferenceResult",
    "ModelStudioProvider",
    "ModelStudioProviderError",
]
