"""Pitwall RunPod client — REST wrapper for Pod and Serverless lifecycle."""

from __future__ import annotations

from importlib import import_module
from typing import Any

from pitwall.core.enums import ProviderType
from pitwall.runpod_client.billing import (
    BillingBucketSize,
    BillingCategory,
    RunPodBillingClient,
    RunPodBillingError,
    RunPodBillingRecord,
)
from pitwall.runpod_client.catalog import (
    CudaVersionAvailability,
    GpuTypeV2,
    ListGpuTypesV2Response,
    RunPodCatalogV2Client,
    RunPodCatalogV2Error,
    list_gpu_types_v2,
)
from pitwall.runpod_client.endpoints import hibernate_endpoint
from pitwall.runpod_client.gpu import (
    CANONICAL_GPU_NAME_MAP,
    CANONICAL_GPU_NAMES,
    CANONICAL_RUNPOD_GPU_NAMES,
    GPU_VRAM_GB,
    LEGACY_GPU_NAME_ALIASES,
    NonCanonicalGPUNameError,
    canonical_gpu_name_suggestions,
    is_canonical_gpu_name,
    non_canonical_gpu_names,
    validate_canonical_gpu_name,
    validate_canonical_gpu_names,
    validate_gpu_type,
    validate_gpu_types,
)
from pitwall.runpod_client.graphql import (
    RUNPOD_GRAPHQL_URL,
    RunpodBidPrice,
    RunpodBidResumeResult,
    RunpodCreditsBalance,
    RunpodDatacenter,
    RunpodGpuAvailability,
    RunpodGpuType,
    RunPodGraphQLClient,
    RunpodGraphQLClient,
    RunpodGraphQLError,
    RunpodGraphQLHTTPError,
    RunpodGraphQLResponseError,
    RunpodLowestPrice,
)
from pitwall.runpod_client.lb import (
    DEFAULT_PROBE_TIMEOUT_S,
    LBClient,
    LBResponse,
    ProbeResult,
    lb_endpoint_url,
)
from pitwall.runpod_client.mounts import (
    POD_MOUNT_PATH,
    POD_PROVIDER_TYPES,
    POD_VOLUME_MOUNT_PATH,
    PROVIDER_TYPE_MOUNT_PATHS,
    PROVIDER_TYPE_VOLUME_MOUNT_PATHS,
    RUNPOD_PROVIDER_TYPES,
    SERVERLESS_MOUNT_PATH,
    SERVERLESS_PROVIDER_TYPES,
    SERVERLESS_VOLUME_MOUNT_PATH,
    NetworkVolume,
    NetworkVolumeClient,
    S3Object,
    mount_path_for_provider_type,
    provider_type_volume_mount_path,
)
from pitwall.runpod_client.pods import (
    DEFAULT_POD_PROBE_TIMEOUT_S,
    NoCapacityError,
    PodProbeResult,
    PodStartupFailed,
    PodStartupTimeout,
    PodVolumeAttachTimeout,
    ProviderAttachHangRecoveryRequested,
    RunPodError,
    RunPodRestError,
    UpdatePodRequest,
    UpdatePodResponse,
    create_pod_with_fallback,
    create_pod_with_fallback_sync,
    get_pod,
    get_pod_strict,
    get_pod_strict_sync,
    get_pod_sync,
    get_pods,
    get_pods_sync,
    reset_pod,
    restart_pod,
    start_pod,
    stop_pod,
    terminate_all_with_tag,
    terminate_pod,
    terminate_pod_sync,
    update_pod,
    wait_for_pod_runtime,
    wait_for_pod_runtime_sync,
)
from pitwall.runpod_client.queue import (
    RUNPOD_API_BASE,
    QueueCancelResult,
    QueueClient,
    QueueHealth,
    QueueJob,
    QueuePurgeResult,
    queue_url,
)
from pitwall.runpod_client.registry import (
    DOCKER_HUB_PREFIX,
    DOCKER_HUB_REGISTRY_AUTH_ENV,
    GHCR_PREFIX,
    GHCR_REGISTRY_AUTH_ENV,
    GITLAB_REGISTRY_AUTH_ENV,
    GITLAB_REGISTRY_PREFIX,
    LEGACY_REGISTRY_AUTH_ENV,
    ContainerRegistryAuth,
    RegistryAuthError,
    create_container_registry_auth,
    delete_container_registry_auth,
    get_container_registry_auth,
    image_registry_prefix,
    list_container_registry_auths,
    registry_auth_env_names_for_image_ref,
    registry_auth_id_from_env,
)
from pitwall.runpod_client.serverless import (
    DEFAULT_MAX_RETRY_AFTER_DELAY_S,
    ServerlessClient,
    ServerlessResponse,
    parse_retry_after,
)
from pitwall.runpod_client.templates import (
    TEMPLATE_NAME,
    config_sha,
    ensure_template,
    get_image_ref_from_env,
    get_registry_auth_id_from_env,
    image_sha,
    non_secret_env_keys,
    normalize_template_name,
    template_display_name,
    template_suffix,
)
from pitwall.runpod_client.workloads import WorkloadConfig

_DISCOVERY_EXPORTS = {
    "DEFAULT_DISCOVERY_TTL_S",
    "DatacenterCatalogEntry",
    "GpuCatalogEntry",
    "GpuDiscoveryService",
    "GpuDiscoverySnapshot",
}


def __getattr__(name: str) -> Any:
    if name in _DISCOVERY_EXPORTS:
        discovery = import_module("pitwall.runpod_client.discovery")
        return getattr(discovery, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [
    "CANONICAL_GPU_NAME_MAP",
    "CANONICAL_GPU_NAMES",
    "CANONICAL_RUNPOD_GPU_NAMES",
    "CudaVersionAvailability",
    "BillingBucketSize",
    "BillingCategory",
    "ContainerRegistryAuth",
    "DOCKER_HUB_PREFIX",
    "DOCKER_HUB_REGISTRY_AUTH_ENV",
    "DEFAULT_DISCOVERY_TTL_S",
    "DEFAULT_MAX_RETRY_AFTER_DELAY_S",
    "DEFAULT_PROBE_TIMEOUT_S",
    "DEFAULT_POD_PROBE_TIMEOUT_S",
    "DatacenterCatalogEntry",
    "GpuCatalogEntry",
    "GpuDiscoveryService",
    "GpuDiscoverySnapshot",
    "GpuTypeV2",
    "GHCR_PREFIX",
    "GHCR_REGISTRY_AUTH_ENV",
    "GITLAB_REGISTRY_AUTH_ENV",
    "GITLAB_REGISTRY_PREFIX",
    "GPU_VRAM_GB",
    "LBClient",
    "LBResponse",
    "LEGACY_REGISTRY_AUTH_ENV",
    "LEGACY_GPU_NAME_ALIASES",
    "ListGpuTypesV2Response",
    "NetworkVolume",
    "NetworkVolumeClient",
    "NoCapacityError",
    "NonCanonicalGPUNameError",
    "POD_MOUNT_PATH",
    "POD_PROVIDER_TYPES",
    "POD_VOLUME_MOUNT_PATH",
    "PROVIDER_TYPE_MOUNT_PATHS",
    "PROVIDER_TYPE_VOLUME_MOUNT_PATHS",
    "RUNPOD_PROVIDER_TYPES",
    "RUNPOD_API_BASE",
    "QueueCancelResult",
    "QueueClient",
    "QueueHealth",
    "QueueJob",
    "QueuePurgeResult",
    "RUNPOD_GRAPHQL_URL",
    "RegistryAuthError",
    "TEMPLATE_NAME",
    "PodStartupFailed",
    "PodStartupTimeout",
    "PodVolumeAttachTimeout",
    "ProviderAttachHangRecoveryRequested",
    "ProviderType",
    "PodProbeResult",
    "ProbeResult",
    "RunPodError",
    "RunPodCatalogV2Client",
    "RunPodCatalogV2Error",
    "RunPodBillingClient",
    "RunPodBillingError",
    "RunPodBillingRecord",
    "RunPodGraphQLClient",
    "RunPodRestError",
    "RunpodBidPrice",
    "RunpodBidResumeResult",
    "RunpodCreditsBalance",
    "RunpodDatacenter",
    "RunpodGpuAvailability",
    "RunpodGpuType",
    "RunpodGraphQLError",
    "RunpodGraphQLClient",
    "RunpodGraphQLHTTPError",
    "RunpodGraphQLResponseError",
    "RunpodLowestPrice",
    "S3Object",
    "SERVERLESS_MOUNT_PATH",
    "SERVERLESS_PROVIDER_TYPES",
    "SERVERLESS_VOLUME_MOUNT_PATH",
    "ServerlessClient",
    "ServerlessResponse",
    "WorkloadConfig",
    "canonical_gpu_name_suggestions",
    "create_container_registry_auth",
    "config_sha",
    "create_pod_with_fallback",
    "create_pod_with_fallback_sync",
    "delete_container_registry_auth",
    "ensure_template",
    "get_container_registry_auth",
    "get_image_ref_from_env",
    "get_pod",
    "get_pod_strict",
    "get_pod_strict_sync",
    "get_pod_sync",
    "get_pods",
    "get_pods_sync",
    "get_registry_auth_id_from_env",
    "hibernate_endpoint",
    "image_registry_prefix",
    "image_sha",
    "is_canonical_gpu_name",
    "lb_endpoint_url",
    "list_gpu_types_v2",
    "list_container_registry_auths",
    "mount_path_for_provider_type",
    "non_canonical_gpu_names",
    "non_secret_env_keys",
    "normalize_template_name",
    "parse_retry_after",
    "provider_type_volume_mount_path",
    "queue_url",
    "registry_auth_env_names_for_image_ref",
    "registry_auth_id_from_env",
    "terminate_all_with_tag",
    "terminate_pod",
    "terminate_pod_sync",
    "template_display_name",
    "UpdatePodRequest",
    "UpdatePodResponse",
    "start_pod",
    "stop_pod",
    "reset_pod",
    "restart_pod",
    "update_pod",
    "template_suffix",
    "validate_canonical_gpu_name",
    "validate_canonical_gpu_names",
    "validate_gpu_type",
    "validate_gpu_types",
    "wait_for_pod_runtime",
    "wait_for_pod_runtime_sync",
]
